services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    plan: free
    rootDir: backend

  - type: static
    name: react-frontend
    env: static
    buildCommand: "npm run build"
    startCommand: "serve -s build"
    plan: free
    rootDir: frontend
